run:
  timeout: 3m

linters-settings:
  gomnd:
    settings:
      mnd:
        ignored-numbers: "0o666,0o777"
  gci:
    sections:
      - standard
      - default
      # FIXME: 実際のテンプレート使用時に変更する。
      - prefix(github.com/kokoichi206-sandbox/go-server-template)
      - blank
      - dot
    skip-generated: false
    # Enable custom order of sections.
    custom-order: true
linters:
  enable-all: true
  disable:
    # New で interface を戻り値とすることを許す。
    - ireturn
    - varnamelen
    - tagliatelle
    - nonamedreturns
    - depguard
    - containedctx
    ## ============ deprecated ============
    - exhaustivestruct
    - exhaustruct
    - golint
issues:
  exclude-rules:
    - path: config/config.go
      linters:
        - funlen
    - linters:
        - goerr113
      text: 'do not define dynamic errors'
